"""
Django settings for shop project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://djangoproject.com

For the full list of settings and their values, see
https://djangoproject.com
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://djangoproject.com

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#gs6njwf75%gbmaz$8bp!jqo15$*b7x_cmqdv@%qh4-_$a&gkx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'orders',
    'cart',
    'myshop',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'shop.wsgi.application'


# Database
# https://djangoproject.com#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://djangoproject.com#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://djangoproject.com

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ==============================================================================
# НАСТРОЙКИ СТАТИКИ И МЕДИАФАЙЛОВ (CSS, JavaScript, Картинки)
# ==============================================================================

# URL для доступа к статическим файлам в браузере
STATIC_URL = 'static/'

# Указывает Django, где искать общую корневую папку static проекта
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# URL для доступа к загружаемым медиафайлам (картинкам товаров) через браузер
MEDIA_URL = '/media/'

# Путь к папке на компьютере, где физически будут сохраняться картинки товаров
MEDIA_ROOT = BASE_DIR / 'media'

CART_SESSION_ID = "cart"