# Generated by Django 6.0.7 on 2026-07-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d', verbose_name='Фото товара'),
        ),
    ]
