# Generated by Django 6.0.7 on 2026-07-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d', verbose_name='Фото товара'),
        ),
    ]
